FROM python:3.9.12-alpine3.14

RUN apk update
RUN apk add v4l-utils
RUN apk add psmisc
RUN apk add mjpg-streamer --repository=http://dl-cdn.alpinelinux.org/alpine/edge/testing

# setup the working directory
WORKDIR /code

# install python dependents
COPY ./requirements.txt /code/requirements.txt
RUN pip install --no-cache-dir --upgrade -r /code/requirements.txt

# copy over app code
COPY ./app /code/app

# run the service
CMD ["uvicorn", "app.main:app", "--host", "0.0.0.0", "--port", "8000"]
