version: '3.8'

services:
  nginx:
    build:
      context: henrypi-nginx
      dockerfile: Dockerfile.alpine
    image: hleong25/henrypi-nginx:alpine
    # restart: always
    ports:
      - 80:80
    depends_on:
      - backend
      - frontend 

  backend:
    build:
      context: henrypi-api
      dockerfile: Dockerfile.alpine
    image: hleong25/henrypi-api:alpine3.14
    privileged: true

  frontend:
    build:
      context: henrypi-ui
      dockerfile: Dockerfile
    image: hleong25/henrypi-ui
