version: '3.8'

services:
  nginx:
    build:
      context: henrypi-nginx
      dockerfile: Dockerfile.alpine
    image: hleong25/henrypi-nginx:alpine
    ports:
      - 80:80
    depends_on:
      - backend

  backend:
    build:
      context: henrypi-api
      dockerfile: Dockerfile.alpine
    image: hleong25/henrypi-api:alpine3.14
    ports:
      - 8000:8000
      - 9000:9000
      - 9001:9001
    privileged: true
    # depends_on:
