version: '3.8'

services:
  nginx:
    image: nginx:1.17
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/conf.d/default.conf
    ports:
      - 80:80
    depends_on:
      - backend

  mjpeg-streamer:
    build:
      context: mjpeg-streamer
      dockerfile: Dockerfile
    image: hleong25/mjpeg-streamer

  backend:
    build:
      context: henrypi-api
      dockerfile: Dockerfile
    image: hleong25/henrypi-api
    # ports:
    #   - 80:80
    #   - 8080:8080
    privileged: true
    depends_on:
      - mjpeg-streamer
