version: '3.8'

services:
  mjpeg-streamer:
    build:
      context: mjpeg-streamer
      dockerfile: Dockerfile
    image: hleong25/mjpeg-streamer

  henrypi-api:
    build:
      context: henrypi-api
      dockerfile: Dockerfile
    image: hleong25/henrypi-api
    ports:
      - 80:80
      - 8080:8080
    privileged: true
    depends_on:
      - mjpeg-streamer
